[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Form handling for Netlify
[[forms]]
  name = "contact"

[[forms]]
  name = "demo-request"
